# Generated by Django 4.2.1 on 2023-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0002_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.TextField(default='https://cdn.imweb.me/upload/S201910012ff964777e0e3/62f9a36ea3cea.jpg'),
        ),
        migrations.AddField(
            model_name='feed',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='profile_image',
            field=models.TextField(default='https://blog.kakaocdn.net/dn/bj4oa7/btqLJWFLMgd/wu4GV8PKbXdICuyW0me0zk/img.jpg'),
        ),
    ]
